
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 12 23:28:13 CST 2017
//----------------------------------------------------

package org.compi2.codigo3d.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int menorigual = 16;
  public static final int MENOS = 6;
  public static final int or_ = 12;
  public static final int DECIMAL = 4;
  public static final int not_ = 14;
  public static final int and_ = 13;
  public static final int POT = 9;
  public static final int ID = 2;
  public static final int igualacion = 19;
  public static final int menor = 18;
  public static final int mayorigual = 15;
  public static final int EOF = 0;
  public static final int MULT = 7;
  public static final int DIV = 8;
  public static final int PAR_IZQ = 10;
  public static final int error = 1;
  public static final int PAR_DER = 11;
  public static final int ENTERO = 3;
  public static final int distinto = 20;
  public static final int MAS = 5;
  public static final int mayor = 17;
}

